name: TCOCI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repo
        uses: actions/checkout@v1

      - name: Send all materials
        uses: appleboy/scp-action@master
        with:
          host: '86.107.198.119'
          username: 'root'
          password: 'Behappy7+'
          port: '22'
          source: 'assets,layouts,components,pages,nuxt.config.js,models,plugins,repositories,services,static,store,package.json,locales'
          target: '/var/www/front/TcoFront'

      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: '86.107.198.119'
          username: 'root'
          password: 'Behappy7+'
          port: '22'
          script: |
            cd /var/www/front/TcoFront
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            yarn install
            yarn build
            pm2 restart all
